name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v4
    - name: Enable Corepack
      run: corepack enable
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install dependencies
      uses: borales/actions-yarn@v5
      with:
        cmd: install
    - name: Build bundle
      uses: borales/actions-yarn@v5
      with:
        cmd: build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist