name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install dependencies
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build